# compose version
version: '3'

# server settings
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5433'
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/simple_docker_rails
    ports:
      - '3001:3000'
    depends_on:
      - db

